### ISSUE TITLE
Export/import parse trees

### ISSUE THREAD

**Issue by dhoepelman** [spreadsheetlab/XLParser#10]
It would be good if we could export/import (serialize/deserialize) parse trees.

Serialization to JSON is already used in the web app. Deserialization could be used in test cases to ensure that the parse tree does not unintendedly change between versions.

**Comment by dhoepelman** [comment]
Export should be very simply to create using a AST visitor (#23) for each format

**Comment by core-code** [comment]
i've added JSON export support based on the web app. let me know if i should submit the patch

**Comment by dhoepelman** [comment]
Certainly interested. If you open a pull request or provide a link to the code we'll take a look.

**Comment by core-code** [comment]
i've just added thisnew  file:
https://gist.github.com/core-code/8a82a51b29035fa031a5

and this method to ExcelFormulaParser.cs
https://gist.github.com/core-code/9feb8ac17fda93e06948

**Comment by dhoepelman** [comment]
Ah I see, I read your message wrong and thought you added import functionality.

For now I feel the JSON export is best left in the wep app codebase, as it is very rudimentary. You are of course free to re-use the code in your projects. Before we add this to the XLParser core it should be a little cleaned up and extended, and preferably provide import functionality.

**Comment by dhoepelman** [comment]
Currently not developing XLParser any more
