### ISSUE TITLE
Support semi-colon List Separator for function arguments

### ISSUE THREAD

**Issue by jj39** [spreadsheetlab/XLParser#100]
a lot of European countries use a semi-colon instead of a comma for separating function arguments. It would be good if your formula parser had a setting that allowed us to set which List Separator character (either ';' or ',') should be used.

https://www.excel-exercise.com/comma-or-semicolon-in-excel-formula/

**Comment by roelvandersteen** [comment]
Hi @jj39 

XLParser will only support non-localized formulas. This means:

- decimal, thousand, and argument/list separator characters at their default values.
- only English function names.
