### ISSUE TITLE
No parser references for structured table references

### ISSUE THREAD

**Issue by WillemJann** [spreadsheetlab/XLParser#102]
See the following file: [Table.xlsx](https://github.com/spreadsheetlab/XLParser/files/4884740/Table.xlsx). This file contains the following formulas:

| Cell | Formula | References.Count() | ParserReferences.Count() |
|-|-|-|-|
| A1 | `=COUNTA(Table1)` | 1 | 1 |
| A2 | `=COUNTA(Table1[#All])` | 1 | 0 |
| A3 | `=COUNTA(Table1[#Data])` | 1 | 0 |
| A4 | `=COUNTA(Table1[#Headers])` | 1 | 0 |
| A5 | `=COUNTA(Table1[#Totals])` | 1 | 0 |
| A6 | `=COUNTA(Table1[@])` | 1 | 0 |
| A7 | `=COUNTA(Table1[Date])` | 1 | 0 |
| A8 | `=COUNTA(Table1[[Date]:[Color]])` | 1 | 0 |
| A9 | `=Table1[[#Headers];[Color]]` | 1 | 0 |
| A10 | `=Table1[[#Totals];[Qty]]` | 1 | 0 |

XLParser correctly recognizes the references. However, the output of the parser references is only correct for the formula in cell A1.

For more complicated table references, no parser references are generated. But the formulas in cell A2-A10 also refer to Table1. The expected result is also one parser reference for these formulas.

**Comment by roelvandersteen** [comment]
The grammar for XLParser was written before Microsoft invented their "structured" table reference syntax. I would welcome a PR to extend the grammar to handle structured table references.

**Comment by WillemJann** [comment]
Fortunately, the grammar of structured table references is already included in XLParser.

I just created a PR #104 to translate the information about structured table references into the `ParserReferences()` method.
