### ISSUE TITLE
Support Internationalization

### ISSUE THREAD

**Issue by dhoepelman** [spreadsheetlab/XLParser#11]
A similar problem to #7, is that Excel changes formulas on different locales.
However, this problem is more constrained. Supporting internationalization entails:
- Replacing delimiters, mainly "," for function arguments and "." for decimal numbers
- Replace error values
- Replace function names

**Comment by dhoepelman** [comment]
Currently not developing XLParser any more

**Comment by MicheleOT** [comment]
@roelvandersteen Hello, I'm currently needing this exact feature, do you know if there's any way to make it work or if it's already implemented in curent version? In my exact case I'm italian and wanted to use numbers like "1,2" (italian and german representation for decimals) in my formulas.
