### ISSUE TITLE
dynamic arrays formula fails to parse

### ISSUE THREAD

**Issue by IainDM** [spreadsheetlab/XLParser#113]
Hi

It looks like this formula = IF(J131 = 1, @INDEX($F125:$F129, J132) / $F130, 0) is not handled by the parser. The issue seems to be the @ sign.

Using Nuget package v1.4.2

**Comment by IainDM** [comment]
This also fails on the web demo, "Error at position 1:16
Syntax error, expected: ,, )"
This is a formula that Excel accepts, but the parser cannot parse.

**Comment by patearl** [comment]
This is also something that we are dealing with. We are considering tackling the change ourselves but are curious whether there has been any effort in supporting the new intersection operator @ already.

https://support.microsoft.com/en-us/office/implicit-intersection-operator-ce3be07b-0101-4450-a24e-c1c999be2b34

**Comment by drmason789** [comment]
I've made a start in my fork of this repo. I'm not sure if it's worthy of a pull request yet. Are you able to see it?
I've provided some parser tests, but am still thinking about what to do for FormulaAnalysisTests.

**Comment by WillemJann** [comment]
Indeed, XLParser should support the implicit intersection operator, and also support spill ranges and spill errors.

@drmason789 looks good, if you create a pull request I'll check and merge this improvement into the main branch.
