### ISSUE TITLE
Issue parsing reference to Cloud-hosted (OneDrive?) locations

### ISSUE THREAD

**Issue by RandomOrangeCat** [spreadsheetlab/XLParser#114]
Hi there!

This is an incredibly useful parser!  However, it throws an exception when trying to parse a formula such as:

**='https://d.docs.live.net/3fade139bf25879f/Documents/[Tracer.xlsx]Sheet2'!$C$5+Sheet10!J44**

where

**https://d.docs.live.net/3fade139bf25879f/Documents/**

is a reference to Documents folder hosted on OneDrive.

Please see the attached image of trying to parse it with the Online Demo.

Even so, this is a massively useful utility! :)

Thanks!
Tim

<img width="1358" alt="XLParser" src="https://user-images.githubusercontent.com/39993756/106392320-2a1cea80-63e9-11eb-8596-33a79e58a5cc.PNG">

**Comment by WillemJann** [comment]
Thank you for reporting. We improved the matching of file paths, including URLs. This formula can now be parsed by XLParser.
