### ISSUE TITLE
Prefix in reference to workbook-level range name is presumed to be a sheet name

### ISSUE THREAD

**Issue by drmason789** [spreadsheetlab/XLParser#117]
This parser does not store the book and sheet names in the workspace, or the book and sheet the formula is in so when a reference like this is  encountered:

=Scope!NamedRange

it assumes that NamedRange is a worksheet-level range name in a sheet called Scope in the same workbook, but it could be a workbook level range name in a different, unsaved (so no file extension) workbook called Scope.

**Comment by WillemJann** [comment]
Correct. The same comment as in #119 applies here, XLParser cannot take any context into account. It does the best guess for this formula, and in most cases it will be a named range at worksheet-level.

Of course you are free to inspect the properties of the parsed reference and correct for the special cases. XLParser does not have that information just by parsing the formula.
