### ISSUE TITLE
Parser is not aware of workbook dimensions

### ISSUE THREAD

**Issue by drmason789** [spreadsheetlab/XLParser#119]
XFD1000 is a cell reference in an xls[xmb] workbook, but is a range name in an xls workbook.

**Comment by WillemJann** [comment]
True. However, XLParser is designed to be a general Excel formula parser and cannot take the context of a workbook into account. This is also the case for Excel functions, it simply parses functions of all Excel versions.

You can of course check the properties of the cell reference after parsing and then draw the conclusion based on your context.
