### ISSUE TITLE
Spill Functions not included in list of built in functions

### ISSUE THREAD

**Issue by drmason789** [spreadsheetlab/XLParser#120]
https://support.microsoft.com/en-us/office/dynamic-array-formulas-and-spilled-array-behavior-205c6b06-03ba-4151-89a1-87a7eb36e531

FILTER
RANDARRAY
SEQUENCE
SORT
SORTBY
UNIQUE

**Comment by WillemJann** [comment]
The new dynamic array functions and spill functions should be detected by XLParser. I'll merge your PR, thank you!
