### ISSUE TITLE
ParserReference.MaxLocation is incorrect for Vertical and Horizontal ranges

### ISSUE THREAD

**Issue by kevinsmith53** [spreadsheetlab/XLParser#123]
`string a1048576 = ExcelFormulaParser.Parse("$A:$A").GetParserReferences().First().MaxLocation; //returns $A100 instead of $A$1048576`

` string xfd1 = ExcelFormulaParser.Parse("$1:$1").GetParserReferences().First().MaxLocation; //returns $CV$1 instead of $XFD$1`

**Comment by WillemJann** [comment]
Thank you for reporting. This is fixed in commit 4cbb7d4.
