### ISSUE TITLE
XLParser does not recognize #GETTING_DATA errors

### ISSUE THREAD

**Issue by PleasantSolutionsDev2** [spreadsheetlab/XLParser#125]
Since it does not recognize #GETTING_DATA as an error token, it can't parse any formulas that contain it, such as `=ERROR.TYPE(#GETTING_DATA)`

**Comment by WillemJann** [comment]
This is indeed a valid error token. I'll merge your PR, thank you!

All [possible error values](https://support.microsoft.com/en-us/office/error-type-function-10958677-7c8d-44f7-ae77-b9a9ee6eefaa) are now in the grammar (ErrorToken and RefErrorToken).
