### ISSUE TITLE
Fail to parse functions with argument outside the parenthesis

### ISSUE THREAD

**Issue by Azure-Vision** [spreadsheetlab/XLParser#127]
Functions like `LOG10()`, `LOG23()`, `LON16()` with argument outside the parenthesis will be parsed as undefined token `UDFToken`

**Comment by WillemJann** [comment]
According to the alphabetical function list ([docs](https://support.microsoft.com/en-us/office/excel-functions-alphabetical-b3944572-255d-4efb-bb96-c6d90033e188)), `LOG` and `LOG10` are valid Excel functions. So these are parsed by XLParser to the `ExcelFunction` token. Other functions like `LOG23` and `LON16` are not valid Excel functions, but they could be custom functions ([docs](https://support.microsoft.com/en-us/office/create-custom-functions-in-excel-2f06c10b-3622-40d6-a1b2-b6748ae8231f)). Therefore XLParser converts these to `UDFTokens`, user defined functions.

As you can see in the [demo](https://xlparser.perfectxl.nl/demo/), XLParser does not fail to parse the functions you demonstrate. Let me know if this clarifies your issue.
