### ISSUE TITLE
Print method is putting space around some operators and causing problems with Evaluate

### ISSUE THREAD

**Issue by terryaney** [spreadsheetlab/XLParser#128]
I parse some formulas, fix some things, then call xlfEvaluate.  However, the `Print` method is putting spaces around items and I'm not sure why or if it should be.  Then, my xlfEvaluate function is failing (not sure why it can't handle spaces).  

For example:

````
ExcelFormulaParser.Parse( "=1+1" ).Print()
"=1 + 1"
````
I guess I'd expect the printed formula to be identical to what was passed in.  Is there a suggested workaround to ensure no spaces are added?

**Comment by terryaney** [comment]
I guess looking at the code:

```
if ( input.IsBinaryOperation() )
{
	// format string for "normal" binary operation
	string format = "{0} {1} {2}";
	if ( input.IsIntersection() )
	{
		format = "{0} {2}";
	}
	else if ( input.IsBinaryReferenceOperation() )
	{
		format = "{0}{1}{2}";
	}

	return string.Format( format, childsL[ 0 ], childsL[ 1 ], childsL[ 2 ] );
}
```

Would just need to change `string format = "{0} {1} {2}";` to `string format = "{0}{1}{2}";`?

**Comment by WillemJann** [comment]
That is correct, this was an error in the Print method. I'll merge your PR, thank you!
