### ISSUE TITLE
Cannot parse some table header references

### ISSUE THREAD

**Issue by WillemJann** [spreadsheetlab/XLParser#132]
The following formula with a reference to a table header can be parsed by XLParser:

```=SUBTOTAL(103,[Column6])```

However, the following formula does not parse:

```=SUBTOTAL(103,[2021])```

Obviously, this reference to a numeric table header is valid in Excel. XLParser should parse this formula.

**Comment by dcrasch** [comment]
The following formula with  reference to a table header cannot be parsed:
```=SUBTOTAL(109,[column header with '[])```

The [ is escaped with a ' and is valid, xlparser should parse this formula.
