### ISSUE TITLE
Cannot parse operations with external links

### ISSUE THREAD

**Issue by WillemJann** [spreadsheetlab/XLParser#136]
XLParser is not able to parse the following formula:

```='\\TEST-01\Folder\[Book1.xlsx]Sheet1'!$A$1+'\\TEST-01\Folder\[Book1.xlsx]Sheet1'!$A$2```

For context, the following formulas can be parsed:

```='\\TEST-01\Folder\[Book1.xlsx]Sheet1'!$A$1```
```='\\TEST-01\Folder\[Book1.xlsx]Sheet1'!$A$2```

**Comment by WillemJann** [comment]
@Pankraty: you made a solution for this issue, that's great! Do you want to make a [pull request](https://github.com/Pankraty/XLParser/pull/new/136-smb-path) for this? I am able to look at it and can merge it into the XLParser codebase as well.

**Comment by Pankraty** [comment]
@WillemJann yeah, this was my intention, but then I realized it does not cover some edge cases (when folder name contains square brackets) and postponed this. I want to get back to the issue after I get more familiar with the Irony library
