### ISSUE TITLE
Column range interpreted as intersection

### ISSUE THREAD

**Issue by jahav** [spreadsheetlab/XLParser#156]
Column ranges ending with 3 letter column ranges (e.g. `=A:AAA`) are interpreted as intersection of the first two letter column range (e.g. A:AA) and a named range with the remaining name (e.g. `A`), but should be interpreted as a really wide column range.

Version 1.5.2.

**Comment by WillemJann** [comment]
Resolved in commit be994bdcefcb0656f109be407619097db833125f. A new version (v1.6.0) has just been released with this fix included.

**Comment by jahav** [comment]
Thank you.
