### ISSUE TITLE
Convert to or dual license with MIT license

### ISSUE THREAD

**Issue by dro123** [spreadsheetlab/XLParser#169]
Is there a chance we can get this library converted to or dual licensed with a MIT license?
It's used in ClosedXML now which uses the MIT license but since this library uses a less permissive license it basically makes it impossible to use ClosedXML in a context where a more permissive license is required.

**Comment by jahav** [comment]
@WillemJann I think you can close this issue. I made a [ClosedParser](https://github.com/ClosedXML/ClosedXML.Parser) that concentrates on performance and AST and ClosedXML will depend on it in the future.

**Comment by WillemJann** [comment]
Thanks for letting us know. We'll close this issue
