### ISSUE TITLE
Unable to parse VLOOKUP with table reference and worksheet reference

### ISSUE THREAD

**Issue by WillemJann** [spreadsheetlab/XLParser#170]
XLParser is unable to parse the following formula:

```=VLOOKUP([@ProductNumber],Sheet2!A:B,1,FALSE)```

However, it it able to parse the following variants (without table reference or without worksheet reference):

```=VLOOKUP(A1,Sheet2!A:B,1,FALSE)```
```=VLOOKUP([@ProductNumber],A:B,1,FALSE)```

**Comment by jahav** [comment]
Please keep in mind that structured references terms are also used for RC formulas (e.g. `SUM(R[1]C[2])`) and that support one way or another for RC addressing is pretty important.

It would be best to have different terms for RC and for structured references.
