### ISSUE TITLE
Parse numbers that start with a decimal point

### ISSUE THREAD

**Issue by kschelfthoutelement** [spreadsheetlab/XLParser#190]
XLParser currently fails to parse numbers that start with a decimal point.

For example `.35 * .76` is a valid formula in Excel but fails in XLParser.

![image](https://github.com/user-attachments/assets/25883cf3-593c-4fb1-8abb-dcebcde35a65)

Thanks!

**Comment by WillemJann** [comment]
Thanks for the PR. The fix is included in XLParser v1.7.3.
