### ISSUE TITLE
Prefixed numbers returned twice

### ISSUE THREAD

**Issue by aivaloglou** [spreadsheetlab/XLParser#21]
```FormulaAnalyzer.Numbers()``` will include twice in the return list the prefixed numbers, e.g. for ```=-8+A1```, both 8 and -8.

**Comment by dhoepelman** [comment]
Cannot reproduce in current master, [testcase](https://github.com/spreadsheetlab/XLParser/compare/test/issue21?expand=1) succeeds. 

        [TestMethod]
        public void NegativeNumber()
        {
            var fa = new FormulaAnalyzer("=-8+A1");
            var nums = fa.Numbers().ToList();
            CollectionAssert.AreEqual(new[] { -8.0 }, nums);
        }

**Comment by dhoepelman** [comment]
This should have been (and seems to be) fixed in [bbb8666c662bb89038a571ee2aea4d48a05164a3](https://github.com/spreadsheetlab/XLParser/commit/bbb8666c662bb89038a571ee2aea4d48a05164a3#diff-bb3afbe4e68d694bdaf3e67ed9e1052eL78), which was included first in 1.1.4

**Comment by aivaloglou** [comment]
Great! I updated my version.
