### ISSUE TITLE
Parse Error with named column ranges

### ISSUE THREAD

**Issue by lanctotsm** [spreadsheetlab/XLParser#27]
=SUM(Table1[@[Word]:[Access]])

I get a parse error when I try to run this through xlparser. The columns in the table are named Word, Excel, etc...  on the sheet and this function returns the sums of all the columns on the table from Word to Access. This is in a Table within a excel document. 

Error at position 1:13
Syntax error, expected: SRColumn, NameToken, [, EnclosedInBracketsToken

**Comment by lanctotsm** [comment]
In the xml it appears as : =SUM(Table1[[#This Row],[Word]:[Access]])

Which does parse :). My problem exists in my code.

**Comment by dhoepelman** [comment]
Unfortunately, the `@` operator is not clearly specified by Excel, and we don't have a (large) dataset of examples. Also See #16

Internally the formula is `SUM(Table1[[#This Row],[Word]:[Access]])`. Accepting `[#This Row],` where `@` exists (within structured references) might work. Larger dataset needed.
