### ISSUE TITLE
support for R1C1 style cell references

### ISSUE THREAD

**Issue by core-code** [spreadsheetlab/XLParser#32]
XLParser does not seem to contain support for R1C1 style cell references.

if i parse 'SUM(R1C1,2)' i get a NamedRangeCombinationToken for R1C1 instead of a CellToken.

we could work work with this and analyze all NamedRangeCombinationToken if they really are a cell reference but it gets worse when analyzing relative R1C1 references

analyzing 'SUM(R[-1]C[2],1)' yields a completely unworkable tree.

since the paper talks about R1C1 style cell reference i was surprised this doesn't seem to work. is there some way to enable them?

**Comment by Felienne** [comment]
Hi @core-code 

Since Excel can provide both versions of the formula, it does not make sense to be able to parse both, hence we do not.

Felienne

**Comment by core-code** [comment]
it very much makes sense for my use-case, i want to be able to parse formulae that contain R1C1 style references!

**Comment by Felienne** [comment]
I understand, but for us it would not be that useful. Is there a way you can have Excel transform the formulas for you? What is the scenario exactly?

**Comment by core-code** [comment]
there is no excel involved, i need to be able to parse excel-compatible formulae for my own spreadsheet application - the formulae are entered by the user and not converted from excel

**Comment by Felienne** [comment]
Ah, got it. If I were you I think I'd write a little converted first and
then use the normal parser. Finding the R1C1 part is probably doable with
regexes.

**Comment by dhoepelman** [comment]
@core-code I agree that there might be useful use-cases, but it is a low priority and can usually be solved otherwise, but you are free to try to support it.

If you wish to build support for this feature your best be to alter the `Cell` nonterminal. Something like this:
    
    private const string R1C1LocationRegex = "((\[\-?[0-9]+\])|([0-9]+))"
    private const string CellR1C1TokenRegex = "R" + R1C1LocationRegex + "?C" +  R1C1LocationRegex + "?";

    public Terminal CellR1C1Token { get; } = new RegexBasedTerminal(GrammarNames.TokenCellR1C1, CellR1C1TokenRegex)
     { Priority = TerminalPriority.CellToken };

    Cell.Rule = CellToken | CellR1C1Token;

You'll also need to do something for row and column ranges at least, maybe more.

**Comment by core-code** [comment]
i can understand if you are not interested in implementing this, but i believe this 
issue should stay open because its a valid request for this project

> Finding the R1C1 part is probably doable with regexes.

huh, do some crude parsing beforehand so that the library designed to do the parsing won't have to do it? not something a self-respecting engineer could implement

> If you wish to build support for this feature your best be to alter the Cell nonterminal. Something like this:

thanks alot, i'll have a look once this becomes higher priority and let you know once i have a working patch

> user to be able to enter it

yes, users should be able to enter formulae in whatever format they prefer

**Comment by Felienne** [comment]
@core-code If you want to update the grammar, go ahead, feel free to reopen. 

I just want to make it clear for us this is not really a concern. 

Also, I disagree the transformation of R1C1 is not a good idea, it will be a short and simple preprocessing step that will keep the parse trees cleaner. This is a trade off, please don't go "self-respecting" on me. Everything has pros and cons.

**Comment by Aleksei-Pankratev-EPAM** [comment]
I wonder how one would parse this formula using regexes:
```
=R[-1]C[1]&SheetR1C1!RC[2]&"Hi, my name is R2C2"
```
Or should we prohibit usage of certain combinations in file paths, workbook names, worksheet names, table and column names, named ranges, string literals and so forth? Does not seem a viable solution.

I agree the issue should have remained open because it is a serious limitation for the parsing library claiming 99.9% compatibility.
