### ISSUE TITLE
IF & CHOOSE are ReferenceFunctionCalls?

### ISSUE THREAD

**Issue by core-code** [spreadsheetlab/XLParser#33]
can someone explain to me why IF & CHOOSE are ReferenceFunctionCalls

INDEX,OFFSET and INDIRECT are the only functions that return references, so guess implementing them as  ReferenceFunctionCalls makes sense.

however, i can not see anything that discerns IF & CHOOSE from other normal excel functions, they just return a value (not reference!) based on their arguments - like any other function.

currently we have a hard time supporting IF/CHOOSE because we end up in the reference code path that expects that a reference is constructed, like INDEX etc do, but IF/CHOOSE do not do that.

what is the rationale to have these two functions as ReferenceFunctionCalls?

we are contemplating pre-processing the string to replace IF/CHOOSE so they won't end up as ReferenceFunctionCalls...

**Comment by dhoepelman** [comment]
`They are reference functions because `IF` and `CHOOSE` can return references: `=SUM( IF(TRUE,A1,A2) : A3)` is a valid function.

**Comment by core-code** [comment]
hm but it doesn't create references, it just passes through (one of) its arguments. 

anyway, thanks for your explanation.

by your logic IFNA and IFERROR should also be ReferenceFunctionCalls

**Comment by dhoepelman** [comment]
We didn't create the language, Microsoft did. It has it's quirks. You can't use `IFNA` in reference expressions so it's not a ReferenceFunctionCall.

**Comment by core-code** [comment]
ok i think i see the difference now... while 
IFNA(NA(),A2)
returns reference to cell A2, you can't combine it with =SUM(IFNA(…) : A3)

thanks for your explanation
