### ISSUE TITLE
Failed parsing table-only structured reference

### ISSUE THREAD

**Issue by aivaloglou** [spreadsheetlab/XLParser#36]
Formulas:

VLOOKUP(GroupVertices[[#This Row],[Vertex]], Vertices[], MATCH("ID", Vertices[#Headers], 0), FALSE)

and

IFERROR(VLOOKUP($A4,TABLA_AHORRO[],6,FALSE),"")

do not parse because of the ```Vertices[]``` and ```TABLA_AHORRO[]``` references

**Comment by dhoepelman** [comment]
Can be fixed by supplying the `NoEscapes` option for strings, and that is correct since Excel doesn't have any escapes and uses doubled quotes instead.

**Comment by dhoepelman** [comment]
Added a rule in `fix_36_allow_table_only_SR` branch. Nice to see that SRs are used at least in the newer datasets.
