### ISSUE TITLE
Failed parsing weird filename

### ISSUE THREAD

**Issue by aivaloglou** [spreadsheetlab/XLParser#38]
Formula:

```'[1].xls].xls]Basic Grant'!A6```

Original formula:

```'C:\Documents and Settings\dwalter\Local Settings\Temporary Internet Files\Content.IE5\GZQER0UH\[FY2014WSSBBasicandFormula[1].xls].xls]Basic Grant'!A6```

in Fuse's 0222dae0-d69a-41f5-8999-9a406a53e4c4 Sheet1!A6, it has been successfully evaluated

**Comment by dhoepelman** [comment]
I don't know how to easily fix this :( , the `]`'s represent a problem.

**Comment by aivaloglou** [comment]
It seems that Excel does not handle ```]```s any more either. In Excel 2010 and 2013 a reference to file ```[FY[1].xls].xlsx``` is inserted as ```='[(FY(1).xls).xlsx]Sheet1'!$A$1```, replacing ```]```s with parentheses.

**Comment by dhoepelman** [comment]
So what do we do with this? ignore it?

**Comment by aivaloglou** [comment]
I think it is safe to ignore it because 
(1) it is an extremely rare case:  in the four datasets that we are currently analyzing, it was found in only 2 out of 370K spreadsheets with formulas, and the parse error was produced in around 50 formulas (3 distinct ) out of 8,5 million and
(2) it will not appear in files created with and later than Excel 2010
