### ISSUE TITLE
Failed parsing quoted external multiple sheets reference

### ISSUE THREAD

**Issue by aivaloglou** [spreadsheetlab/XLParser#47]
Formula:

SUM('[74]Miami P&L:Venezuela P&L'!G10)

its original:
=SUM('D:\TV_LATAM_NET_ACC\Financial Statement Comments\Ad Sales\FY''15\Period 3\[3-Ad Sales Financial Statements FY15 June-v2.xlsx]Miami P&L:Venezuela P&L'!G10)

**Comment by dhoepelman** [comment]
Fixed by changing the quoted multiple sheets parsing to be the same as normal quoted sheet parsing
