### ISSUE TITLE
Mixed escape characters for excel formulas

### ISSUE THREAD

**Issue by lanctotsm** [spreadsheetlab/XLParser#51]
Using the test string : IF(A8>0,12*$B$2-D8,"0\") I get a non-terminated string literal error. Excel parses this formula fine, and treats the backslash as a literal character resulting in the output 0. The parser shouldn't be treating the backslash as an escape character here.

**Comment by ThunderFrame** [comment]
I can't see a backslash in your test string, and I don't know how to view the raw markdown. Are you able to repost, and ensure the backslash is rendered? You can surround a \\ with the \` code-delimiter character, or use a leading \\ character to escape each \\ as \\\\:

4 trailing backslashes inside 2 \` code delimiters 
`IF(A8>0,12*$B$2-D8,"0")\\\\`

4 escaped trailing backslashes (8 backslashes in total)
IF(A8>0,12*$B$2-D8,"0")\\\\\\\\

**Comment by ThunderFrame** [comment]
I *think* I can reproduce the error on the website with this:

`=IF(A8>0,12*$B$2-D8,"0\")`

```text
Error at position 1:20
Mal-formed  string literal - cannot find termination symbol.
```

Escaping the \\ with a leading \\ works fine, so it's not immediately clear to me whether this is an HTML/javascript encoding issue, or an XLParser issue:
`IF(A8>0,12*$B$2-D8,"0\\")`

**Comment by roelvandersteen** [comment]
This is confirmed not to be an XLParser issue. See https://github.com/roelvandersteen/XLParser/commit/14d2b31a520e071a13a0b49d83ffe520975578d0.
