### ISSUE TITLE
Demo site/domain is down

### ISSUE THREAD

**Issue by terryaney** [spreadsheetlab/XLParser#52]
Was trying to view the demo site to show features and compatibility to work group but says there is a DNS server error.

**Comment by terryaney** [comment]
I guess this affects the documentation too.

**Comment by aivaloglou** [comment]
Thank you for letting us know.
Some changes to our DNS caused this. It is fixed now.

**Comment by terryaney** [comment]
FYI, doesn't come up for me yet.  I've no DSN background so not sure if cached on my end or what, but doesn't come up in Mac Safari, Win Chrome or IE.

**Comment by joerivv** [comment]
Give it a day, it propagates more slowly on some servers. It shouldn't be much longer.
