### ISSUE TITLE
Unable to parse UDF function on broken link

### ISSUE THREAD

**Issue by terryaney** [spreadsheetlab/XLParser#53]
I dumped out a range.Formula to attempt to parse it and got something like this...

`=IF(age_now>P14, "N/A",'C:\Program Files\Microsoft Office 15\root\office15\Library\CFGENA\Cfgena.xla'!SSTableProj(YEAR(dob),...`

I get a full path because the Cfgena.xla addin was currently not loaded, but I'm hoping to still be able to parse it.  When I attempt to parse the formula, I get:

(1,28) Syntax error, expected: EnclosedInBracketsToken

If I wrap the entire 'path' in ['path'], it works.  Since Excel is the one giving me the formula, is there any way to make the parser handle this without the []?

Thanks in advance.

**Comment by roelvandersteen** [comment]
Fixed in PR #86
