### ISSUE TITLE
Function names with special characters break the parser

### ISSUE THREAD

**Issue by ThunderFrame** [spreadsheetlab/XLParser#55]
This is a perfectly valid, albeit somewhat evil, VBA function (although the character, being extended ASCII, may vary according to the VBA project/VBE codepage):

```vb
Public Function ·()
  · = 5
End Function
```
And works just fine in an Excel formula:

```text
=·()
5
```

But using the online parser, I get error:

>Error at position 1:2
Syntax error, expected: CellToken, NameToken, NamedRangeCombinationToken, VRangeToken, HRangeToken, RefErrorToken, UDFToken, [, EnclosedInBracketsToken, (, ExcelRefFunctionToken, ExcelConditionalRefFunctionToken, SheetNameToken, ', FileNameNumericToken, FilePathWindowsToken, MultipleSheetsToken, NumberToken, TextToken, BoolToken, ErrorToken, ExcelFunction, +, -, {, ReservedNameToken

**Comment by roelvandersteen** [comment]
It appears that you can use the following special characters in your UDF names:

```
¡¢£¤¥¦§¨©«¬­®¯°±²³´¶·¸¹»¼½¾¿×÷
```
