### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by igitur** [spreadsheetlab/XLParser#60]
Any plans to implement .NET Standard?

Context: We at http://github.com/ClosedXML/ClosedXML would like to use XLParser to parse the Excel formulae, but are planning to support .NET Standard.

**Comment by igitur** [comment]
I guess Irony will have to support .NET Standard first before XLParser can. There is a fork at https://github.com/daxnet/irony -  @rivantsov , is your original fork dead or would you ever merge @daxnet 's changes?

**Comment by rivantsov** [comment]
from rivantsov - no, it's not my fork. As codeplex closes, I am planning to move copy of Irony to github, and then start Irony2, complete restart, but this would be years in making I guess. If you need .net core version now, I think it would be quite easy to move base assemblies, I did not use any platform-specific stuff (I think)

**Comment by igitur** [comment]
Thanks @rivantsov .  But would you consider merging @daxnet 's commits into your official repo?

**Comment by igitur** [comment]
@spreadsheetlab I'll submit a PR for .NET Standard 1.6 compatibility soon. There doesn't seem to be any major code issues.

**Comment by raffaeler** [comment]
@igitur Take this as a suggestion, nothing more, but targeting netstandard 1.5 gives you more frameworks than 1.6.
While 1.4 api surface is very poor, the 1.5 is slightly smaller in comparison to 1.6 and allows any library user to target for more 4.x framework flavors.

**Comment by igitur** [comment]
@raffaeler For now I targeted 1.6 - just to get a PR in. If it's accepted, we can look at switching to 1.5, as you recommend.

**Comment by igitur** [comment]
There is a dependency on Irony, which currently builds 1.6.
