### ISSUE TITLE
Include new Excel functions from v2010 v2013 v2016

### ISSUE THREAD

**Issue by roelvandersteen** [spreadsheetlab/XLParser#63]
The function list in XLParser has not been updated for a while. Excel v2010, v2013 and v2016 introduced quite a few new functions. See

-   https://support.office.com/en-us/article/What-s-New-Changes-made-to-Excel-functions-355d08c8-8358-4ecb-b6eb-e2e443e98aac
-   https://support.office.com/en-us/article/New-functions-in-Excel-2013-075c82bd-15b9-4ad6-af31-55bb6b011cb9
-   https://support.office.com/en-us/article/What-s-new-in-Excel-2016-for-Windows-5fdb9208-ff33-45b6-9e08-1f5cdb3a6c73 (under January 2016 updates)

Incorporate these functions in the ExcelBuiltinFunctionsList, so that they will not be parsed as user defined functions.

**Comment by roelvandersteen** [comment]
See PR #64

**Comment by dhoepelman** [comment]
#64 has been merged and published in 1.3.1
