### ISSUE TITLE
Error parsing structured reference

### ISSUE THREAD

**Issue by Thinqer77** [spreadsheetlab/XLParser#67]
Hi,

Just came across your parser and am liking what I'm seeing - I've built one in VBA based on Rob Van Gelder's and have come across a few formulae that cause problems, so thought I'd try them out on yours...

The following formula is accepted in Excel (2013) but returns an error on your web based parser:

=COUNT(Table1[@['#]:['@]])

Note that there is a simple table called Table1 with a column labelled '#' and a column labelled '@' (both without quote marks) and the formula was constructed by trying to count all items from one column to the other on a particular row. I deliberately named the columns that way because those symbols are used as special characters in structured references so wanted to see if I could break either Excel or my parser ;-)

The error was:

Error at position 1:15
Syntax error, expected: SRColumn, NameToken, [, EnclosedInBracketsToken

Will have a dig about in some of my old test files to see if there's anything else that proves problematic.

Thanks,

Ben.

[Proposed label: parse error]

**Comment by JackWightonSimpson** [comment]
actually this fails in the case of something like =SUM(table[@[c1]:[c3]])
weird column names are not needed (they are actually parsed successfully).

**Comment by roelvandersteen** [comment]
Merged in [roelvandersteen/XLParser](https://github.com/roelvandersteen/XLParser). Thank you for your contribution.
