### ISSUE TITLE
ExcelBuiltinFunctionList.txt misses several functions and has some errors

### ISSUE THREAD

**Issue by hell-racer** [spreadsheetlab/XLParser#70]
These functions are not in the list, thus they are parsed as UDFs:

DATEDIF
DBCS
FINDB
ISERR
ISEVEN
ISLOGICAL
ISNONTEXT
ISODD
ISREF
ISTEXT (see #68)

Errors:

EDATEEFFECT should be two functions: EDATE and EFFECT
ORECAST.ETS.CONFINT should be FORECAST.ETS.CONFINT (starts with F)

Should I create a pull request?

**Comment by roelvandersteen** [comment]
Submitted to NuGet as version 1.3.4.

Version 1.3.4 has been published from this fork: https://github.com/roelvandersteen/EPPlus

**Comment by hell-racer** [comment]
Are you sure about roelvandersteen/EPPlus? Not the roelvandersteen/XLParser?

**Comment by roelvandersteen** [comment]
You are right. I updated the link.

**Comment by hell-racer** [comment]
Thank you! Do I understand correctly this main fork spreadsheetlab/XLParser is no longer maintained and in case if I have issues/PRs/comments I have to head over to your fork roelvandersteen/XLParser?

**Comment by igitur** [comment]
@roelvandersteen Why has XLParser been forked? The many forks of Irony is already confusing, now XLParser is forked too? Can't we get the community efforts consolidated?

**Comment by hell-racer** [comment]
Maybe because it is no longer maintained?

**Comment by igitur** [comment]
But as per #61, all he had to do was ask for access. Don't worry, I'll take up his offer and get this sorted.

**Comment by dhoepelman** [comment]
@roelvandersteen do you not have commit acccess? @Felienne can probably give them to you

**Comment by hell-racer** [comment]
Fixed in 1.3.4
