### ISSUE TITLE
Error parsing table column with numeric name

### ISSUE THREAD

**Issue by JackWightonSimpson** [spreadsheetlab/XLParser#72]
Formulas such as ```=SUM(Table[1])``` fail when the column name contains only digits, but are supported in at least recent versions of excel.

**Comment by roelvandersteen** [comment]
I have added your example to the test set (see roelvandersteen/XLParser@0b1af50f), but the formula is parsed without problems. Can you please clarify what the exact problem is?

**Comment by roelvandersteen** [comment]
No further comments received from the OP.
