### ISSUE TITLE
Double reference node when parsing long formula

### ISSUE THREAD

**Issue by davidbirchwork** [spreadsheetlab/XLParser#78]
=(YEAR(I15)-YEAR(C4))*12+MONTH(I15)-MONTH(C4)+IF(MONTH(I15)-MONTH(C4)>=0, IF((DAY(I15)-DAY(C4))>25, 1,( IF(DAY(I15)-DAY(C4)<-5, -1,0))), IF((DAY(I15)-DAY(C4))>25, 1, IF((DAY(I15)-DAY(C4))<-25, -1,0))) 

This may or may not be expected behavior 

![image](https://user-images.githubusercontent.com/11289564/52269001-ddef5a80-2934-11e9-81ff-e812c5a7cc11.png)

**Comment by roelvandersteen** [comment]
Yes, this is to be expected, and also correct. The extra reference node refers to an extra set of parentheses in the formula:

```
=(
  YEAR(I15) - YEAR(C4)
)
* 12
+ MONTH(I15) - MONTH(C4)
+ IF(
  MONTH(I15) - MONTH(C4) >= 0,
  IF(
    (DAY(I15) - DAY(C4)) > 25,
    1,
    →(← IF(DAY(I15) - DAY(C4) < -5, -1, 0) →)←
  ),
  IF(
    (DAY(I15) - DAY(C4)) > 25,
    1,
    IF( →(← DAY(I15) - DAY(C4) →)← < -25, -1, 0)
  )
)
```
