### ISSUE TITLE
Parser fails on formulas with addin (.xla) explicit references

### ISSUE THREAD

**Issue by JulioNobre** [spreadsheetlab/XLParser#84]
If one tries to parse  then following formula, an exception will be raised:

='C:\MyAddins\MyAddin.xla'!MyFunc("sampleTextArg", 1)

**Comment by roelvandersteen** [comment]
This issue is confirmed. The culprit is a backslash between the quotes.

**Comment by JulioNobre** [comment]
Hi @roelvandersteen
Justa to let you that it happened in a real world situations and thank for acknowledge it! 👍
