### ISSUE TITLE
Wrong parse of 0 + 48060.774 + 0 + -172808.43 + 0

### ISSUE THREAD

**Issue by gustavolealgtz** [spreadsheetlab/XLParser#90]
Hi,

I tested the following formula in Excel ( `0 + 48060.774 + 0 + -172808.43 + 0` ) and get **-124748** as result but in your live web demo, the value -17808.43 is getting as positive (NumberToken : 17808.43), so, I assume it will get wrong result in XLParser.

Also I tested basic formula `48060.774 + (-172808.43)` with the same result in XLParser.

Regards
Gustavo Leal

**Comment by roelvandersteen** [comment]
The parse tree is constructed a bit different than you think. A negative constant value is seen as a *function*, consisting of the unary operator "minus", and the numbertoken containing the value. See the relevant section in the parse tree below.

![parsetree](https://user-images.githubusercontent.com/3676835/75012707-db4d9d80-5482-11ea-9723-0346495eedfe.png)
