### ISSUE TITLE
Submit result to Calculator or Execute function after parse to compute in C# middleware

### ISSUE THREAD

**Issue by weedkiller** [spreadsheetlab/XLParser#94]
Hello, can you add an compute or  `Parser.Parse.Evaluate<decimal>()` like [here](https://github.com/zzzprojects/Eval-Expression.NET) or even this free [webshell](https://github.com/davideicardi/DynamicExpresso)

Or can you please share some guidance on how this would be passed to that evaluator or a calculator

**Comment by roelvandersteen** [comment]
Sorry @weedkiller, that's not gonna work. The XLParser is just a parser, there is no further logic to interpret or execute the parsed result. The parser tree cannot just be translated into C# code.

Alternatives are:

- [ClosedXml](https://github.com/ClosedXML/ClosedXML) can evaluate Excel formulas as [explained here](https://github.com/ClosedXML/ClosedXML/wiki/Evaluating-Formulas).
- EPPlus](https://github.com/JanKallman/EPPlus) also has a calculation engine for Excel formulas. (The link refers to the LGPL version of EPPlus, there is a [newer version](https://www.epplussoftware.com) with a more restrictive license).
- Several commercial Excel libraries may also have a calculation engine for Excel formulas. My current favorite is the expensive [Aspose.Cells for .NET](https://products.aspose.com/cells/net), with calculation capabilities explained on [this help page](https://docs.aspose.com/display/cellsnet/Ways+to+Calculate+Formulas).

**Comment by weedkiller** [comment]
Thanks
